# Generated by Django 5.1.6 on 2025-03-05 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_user_age_user_email_user_location_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
    ]
