# Generated by Django 5.1.6 on 2025-03-05 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_user_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
    ]
