# Generated by Django 5.1.6 on 2025-03-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_column='Book-Title', max_length=255, null=True)),
                ('author', models.CharField(blank=True, db_column='Book-Author', max_length=255, null=True)),
                ('year_of_publication', models.IntegerField(blank=True, db_column='Year-Of-Publication', null=True)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url_s', models.URLField(blank=True, db_column='Image-URL-S', max_length=255, null=True)),
                ('image_url_m', models.URLField(blank=True, db_column='Image-URL-M', max_length=255, null=True)),
                ('image_url_l', models.URLField(blank=True, db_column='Image-URL-L', max_length=255, null=True)),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
